CREATE USER scala WITH PASSWORD 'scala';
CREATE DATABASE scaladb with OWNER=scala;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO scala;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO scala;
-- GRANT ALL ON SCHEMA public TO scala;
-- GRANT ALL ON SCHEMA public TO public;
